// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux: // ✅ Added Linux here
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCyccKmcCJDhRJyg-DHypDBw05Yi3zjPE',
    appId: '1:819917133190:web:6ee1932e9326d0474f8807',
    messagingSenderId: '819917133190',
    projectId: 'kacchya-kotha',
    authDomain: 'kacchya-kotha.firebaseapp.com',
    storageBucket: 'kacchya-kotha.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCyccKmcCJDhRJyg-DHypDBw05Yi3zjPE',
    appId: '1:819917133190:web:1ea180710fb646b74f8807',
    messagingSenderId: '819917133190',
    projectId: 'kacchya-kotha',
    authDomain: 'kacchya-kotha.firebaseapp.com',
    storageBucket: 'kacchya-kotha.firebasestorage.app',
  );
}
